import { Box, Card, Container, Text, Title } from "@mantine/core";
import Head from "next/head";
import { PageWrapper } from "../components/PageWrapper/PageWrapper";
import { TodaysLessons } from "../components/pages/Dashboard/TodaysLessons";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <h1>Dashboard</h1>
        <Container>
          <Box maw={340} mx="auto">
            <TodaysLessons />
          </Box>
        </Container>
      </PageWrapper>
    </>
  );
};
export default Home;
