import Head from "next/head";
import { PageWrapper } from "../components/PageWrapper/PageWrapper";

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <h1>Home</h1>
      </PageWrapper>
    </>
  );
};
export default Home;
