version: "3.8"
services:
  db:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_PWD}
      MONGO_INITDB_DATABASE: ${DOCKER_MONGO_DBNAME}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db