name: Cypress Tests
env:
  VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
  VERCEL_PROJECT_ID: "${{ secrets.VERCEL_PROJECT_ID }}"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  ATLAS_DB: "${{ secrets.ATLAS_DB }}"
  CALENDLY_API_KEY: "${{ secrets.CALENDLY_API_KEY }}"
  CALENDLY_WEBHOOK_SIGNING_KEY: "${{ secrets.CALENDLY_WEBHOOK_SIGNING_KEY }}"
  HYGRAPH_API_KEY: "${{ secrets.HYGRAPH_API_KEY }}"
  NEXT_PUBLIC_SENTRY_DSN: "${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}"
  SENDGRID_DEV_API_KEY: "${{ secrets.SENDGRID_DEV_API_KEY }}"
  SENTRY_AUTH_TOKEN: "${{secrets.SENTRY_AUTH_TOKEN }}"
  SENTRY_DSN: "${{ secrets.SENTRY_DSN }}"
  STRIPE_TEST_PUBLISHABLE_KEY: "${{ secrets.STRIPE_TEST_PUBLISHABLE_KEY }}"
  STRIPE_TEST_SECRET_KEY: "${{ secrets.STRIPE_TEST_SECRET_KEY }}"
  STRIPE_WEBHOOK_SECRET: "${{ secrets.STRIPE_WEBHOOK_SECRET }}"
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build
      - name: E2E on Chrome
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:3000"
      - name: Uploading Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: "cypress-screenshots"
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - name: Uploading Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
