name: Unit Tests
env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  TEST_ENV: 1
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel env pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} && echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:ci
