name: Unit Tests
env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  TEST_ENV: 1
on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:ci
