# name: Unit Tests
# env:
#   GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#   TEST_ENV: 1
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
# on: [pull_request]
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   unit-tests:
#     runs-on: ubuntu-latest
#     environment: preview
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Start containers
#         run: docker-compose -f "docker-compose.yml" up -d --build
#         env:
#           DOCKER_MONGO_USERNAME: ${{ secrets.DOCKER_MONGO_USERNAME }}
#           DOCKER_MONGO_PWD: ${{ secrets.DOCKER_MONGO_PWD }}
#           DOCKER_MONGO_DBNAME: test

#       - name: Install Vercel CLI
#         run: npm install --global vercel@latest

#       - name: Pull Vercel Environment Information
#         run: vercel env pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

#       - name: Dotenv Mount
#         uses: falti/dotenv-action@v1.0.4
#         with:
#           path: .env
#           mask-variables: true
#           export-variables: true
#           keys-case: upper

#       - name: Install dependencies
#         run: npm install

#       - name: Run Tests
#         run: npm run test:ci
#         env:
#           DATABASE_URL: ${{ secrets.DOCKER_DATABASE_URL }}

#       - name: Stop containers
#         if: always()
#         run: docker-compose -f "docker-compose.yml" down

